version: '3.8'

services:
  training-management-app-quick:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install --silent && npm run dev -- --host"
    restart: unless-stopped

